---
include:
  - project: 'guidog/meta-phosh'
    ref: '7e4c54478a07dfa3df0867a3c7be067cd254165d'
    file: '/ci/phosh-common-jobs.yml'
  - remote: 'https://gitlab.freedesktop.org/freedesktop/ci-templates/-/raw/6a40df92957c8ce9ee741aaccc5daaaf70545b1e/templates/ci-fairy.yml'

stages:
  - build
  - test
  - style-checks
  - package

default:
  # Protect CI infra from rogue jobs
  timeout: 15 minutes
  # Allow jobs to be caneled on new commits
  interruptible: true
  # Retry on infra hickups automatically
  retry:
    max: 1
    when:
      - 'api_failure'
      - 'runner_system_failure'
      - 'scheduler_failure'
      - 'stuck_or_timeout_failure'

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    # Don't trigger a branch pipeline if there is an open MR
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

variables:
  # For ci-fairy
  FDO_UPSTREAM_REPO: guidog/xdg-desktop-portal-phosh
  DEBIAN_IMAGE: debian:forky
  COMMON_BUILD_OPTS: --werror
  PHOSH_DOCKER_IMAGE: debian:forky

.forky_vars: &forky_vars
  variables:
    DIST: forky
    BUILD_OPTS: ${COMMON_BUILD_OPTS}
    PHOSH_ADDITIONAL_PKGS: docutils-common git

.build_step: &build_step
  script:
    - !reference [.phosh-prepare-apt]
    - eatmydata apt-get -y build-dep .
    - 'echo "Build opts: ${BUILD_OPTS}"'
    - meson ${BUILD_OPTS} . _build
    - meson compile -C _build

build:native-debian-forky:
  stage: build
  image: ${DEBIAN_IMAGE}
  <<: *forky_vars
  <<: *build_step
  artifacts:
    paths:
      - _build

check-po:
  stage: test
  extends: .phosh-check-po

check-consistency:
  stage: test
  extends: .phosh-check-consistency

run-rustfmt:
  stage: style-checks
  image: ${DEBIAN_IMAGE}
  needs: []
  script:
    - apt-get update && apt-get install rustup -y
    - rustup default stable
    # Our rustfmt.toml uses nightly features
    - rustup toolchain install nightly
    - rustup component add rustfmt --toolchain nightly
    # Generated by Meson during build time, so use placeholder files
    - printf "\n" > src/lib_config.rs && printf "\n" > src/bin_config.rs
    - cargo +nightly fmt --check

run-clippy:
  stage: test
  image: ${DEBIAN_IMAGE}
  needs: []
  <<: *forky_vars
  script:
    # Clippy will compile the project, so needs real files with all dependencies.
    - !reference [.build_step, script]
    - eatmydata apt-get install -y rust-clippy
    - CARGO_HOME=_build/cargo RESOURCES_DIR=$PWD/_build/src cargo clippy --no-deps -- -Dclippy::pedantic

check-format:
  stage: style-checks
  extends: .phosh-format-check
  allow_failure: true

check-markdown:
  stage: style-checks
  variables:
    PHOSH_MARKDOWN_PATHS: "*.md"
  extends:
    - .phosh-check-markdown

check-meson:
  stage: style-checks
  image: ${PHOSH_DOCKER_IMAGE}
  extends:
    - .phosh-check-meson

sanity:
  extends:
    - .fdo.ci-fairy
  stage: style-checks
  needs: []
  script: |
    ci-fairy check-commits --signed-off-by --junit-xml=commit-message-junit-report.xml
  artifacts:
    reports:
      junit: commit-message-junit-report.xml
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME'

package:deb-debian-forky:
  stage: package
  extends: .phosh-build-debian-package
